---
openapi: 3.1.1
info:
  title: Invoice management system
  version: 1.0.0
  description: Demo application to manage invoices
tags:
  - name: Invoice
paths:
  /invoice/{invoiceId}:
    get:
      description: Get a invoice
      operationId: getInvoice
      parameters:
        - in: path
          name: invoiceId
          description: Id of the invoice
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Successfully fetched the invoice
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvoiceResponse'
  /invoice:
    post:
      summary: Create a new invoice
      operationId: createInvoice
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InvoiceRequest'
      responses:
        '201':
          description: Successfully created invoice
          content:
            application/json:
                schema:
                  type: integer
                  format: int64

components:
  schemas:
    InvoiceRequest:
      type: object
      required:
        - invoiceNumber
        - issueDate
        - dueDate
        - totalNet
        - totalVat
        - totalGross
        - client
        - items
      properties:
        invoiceNumber:
          type: string
          maxLength: 50
        issueDate:
          type: string
          format: date
        dueDate:
          type: string
          format: date
        totalNet:
          type: number
          format: double
          minimum: 0
          maximum: 9999999999.99
        totalVat:
          type: number
          format: double
          minimum: 0
          maximum: 9999999999.99
        totalGross:
          type: number
          format: double
          minimum: 0
          maximum: 9999999999.99
        client:
          $ref: '#/components/schemas/ClientRequest'
        items:
          type: array
          items:
            $ref: '#/components/schemas/InvoiceItemRequest'


    InvoiceResponse:
      allOf:
        - $ref: '#/components/schemas/InvoiceRequest'
        - type: object
          required:
            - id
            - createdAt
            - client
            - items
          properties:
            id:
              type: integer
              format: int64
            createdAt:
              type: string
              format: date-time
            client:
              $ref: '#/components/schemas/ClientResponse'
            items:
              type: array
              items:
                $ref: '#/components/schemas/InvoiceItemResponse'

    ClientRequest:
      type: object
      required:
        - name
        - nip
      properties:
        name:
          type: string
          maxLength: 255
        nip:
          type: string
          maxLength: 20
        address:
          type: string
          maxLength: 255
        email:
          type: string
          format: email
        phone:
          type: string
          maxLength: 20

    ClientResponse:
      allOf:
        - $ref: '#/components/schemas/ClientRequest'
        - type: object
          required:
            - id
          properties:
            id:
              type: integer
              format: int64

    InvoiceItemRequest:
      type: object
      required:
        - description
        - quantity
        - netPrice
        - vatRate
      properties:
        description:
          type: string
        quantity:
          type: number
          format: double
        unitPrice:
          type: number
          format: double
        vatRate:
          type: number
          format: double
        netValue:
          type: number
          format: double
          readOnly: true
        vatValue:
          type: number
          format: double
          readOnly: true
        grossValue:
          type: number
          format: double
          readOnly: true

    InvoiceItemResponse:
      allOf:
        - $ref: '#/components/schemas/InvoiceItemRequest'
        - type: object
          required:
            - id
          properties:
            id:
              type: integer
              format: int64