---
openapi: 3.0.0
info:
  title: Invoice management system
  version: 1.0.0
  description: Demo application to manage invoices
tags:
  - name: Invoice
paths:
  /invoice/{invoiceId}:
    get:
      summary: Get a invoice
      operationId: getInvoice
      parameters:
        - in: path
          name: invoiceId
          description: Id of the invoice
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Successfully fetched the invoice
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvoiceResponse'
  /invoice:
    get:
      summary: Get paginated invoices
      operationId: getInvoices
      parameters:
        - in: query
          name: page
          schema:
            type: integer
            minimum: 0
          description: Zero-based page index (0..N)
        - in: query
          name: size
          schema:
            type: integer
            minimum: 1
          description: The size of the page to be returned
      responses:
        "200":
          description: Paginated invoices
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PaginatedInvoiceResponse"

    post:
      summary: Create a new invoice
      operationId: createInvoice
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InvoiceRequest'
      responses:
        '201':
          description: Successfully created invoice
          content:
            application/json:
                schema:
                  type: integer
                  format: int64
  /client:
    get:
      summary: Get paginated clients
      operationId: getClients
      parameters:
        - in: query
          name: page
          schema:
            type: integer
            minimum: 0
          description: Zero-based page index (0..N)
        - in: query
          name: size
          schema:
            type: integer
            minimum: 1
          description: The size of the page to be returned
      responses:
        "200":
          description: Paginated clients
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedClientResponse'
    post:
      summary: Create a new client
      operationId: createClient
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ClientRequest'
      responses:
        '201':
          description: Successfully created client
          content:
            application/json:
              schema:
                type: integer
                format: int64

  /client/exists:
    get:
      summary: Check if client NIP exists
      operationId: checkClientNipExists
      parameters:
        - in: query
          name: nip
          required: true
          schema:
            type: string
          description: The NIP of the client to check
      responses:
        '200':
          description: Return whether client exists
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CheckClientNipExistsResponse'
components:
  schemas:
    InvoiceRequest:
      type: object
      required:
        - invoiceNumber
        - issueDate
        - dueDate
        - client
        - items
      properties:
        invoiceNumber:
          type: string
          maxLength: 50
        issueDate:
          type: string
          format: date
        dueDate:
          type: string
          format: date
        totalNet:
          type: number
          format: double
          minimum: 0
          maximum: 9999999999.99
          readOnly: true
        totalVat:
          type: number
          format: double
          minimum: 0
          maximum: 9999999999.99
          readOnly: true
        totalGross:
          type: number
          format: double
          minimum: 0
          maximum: 9999999999.99
          readOnly: true
        client:
          $ref: '#/components/schemas/ClientRequest'
        items:
          type: array
          items:
            $ref: '#/components/schemas/InvoiceItemRequest'


    InvoiceResponse:
      allOf:
        - $ref: '#/components/schemas/InvoiceRequest'
        - type: object
          properties:
            id:
              type: integer
              format: int64
            createdAt:
              type: string
              format: date-time
            client:
              $ref: '#/components/schemas/ClientResponse'
            items:
              type: array
              items:
                $ref: '#/components/schemas/InvoiceItemResponse'

    ClientRequest:
      type: object
      required:
        - name
        - nip
      properties:
        name:
          type: string
          minLength: 1
          maxLength: 255
        nip:
          type: string
          minLength: 1
          maxLength: 20
        address:
          type: string
          maxLength: 255
          readOnly: true
        email:
          type: string
          format: email
          readOnly: true
        phone:
          type: string
          maxLength: 20
          readOnly: true

    ClientResponse:
      allOf:
        - $ref: '#/components/schemas/ClientRequest'
        - type: object
          properties:
            id:
              type: integer
              format: int64

    InvoiceItemRequest:
      type: object
      required:
        - description
        - quantity
        - unitPrice
      properties:
        description:
          type: string
        quantity:
          type: integer
          format: int64
          minimum: 1
        unitPrice:
          type: number
          format: double
        vatRate:
          type: number
          format: double
          default: 23
          readOnly: true
        netValue:
          type: number
          format: double
          readOnly: true
        vatValue:
          type: number
          format: double
          readOnly: true
        grossValue:
          type: number
          format: double
          readOnly: true

    InvoiceItemResponse:
      allOf:
        - $ref: '#/components/schemas/InvoiceItemRequest'
        - type: object
          properties:
            id:
              type: integer
              format: int64

    PaginatedInvoiceResponse:
      type: object
      properties:
        content:
          type: array
          items:
            $ref: '#/components/schemas/InvoiceResponse'
        totalElements:
          type: integer
          format: int64
        totalPages:
          type: integer
          format: int32
        number:
          type: integer
          format: int32
        size:
          type: integer
          format: int32

    PaginatedClientResponse:
      type: object
      properties:
        content:
          type: array
          items:
            $ref: '#/components/schemas/ClientResponse'
        totalElements:
          type: integer
          format: int64
        totalPages:
          type: integer
          format: int32
        number:
          type: integer
          format: int32
        size:
          type: integer
          format: int32

    CheckClientNipExistsResponse:
      type: object
      properties:
        exists:
          type: boolean
